AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  testLambdaCloudWatchEvent:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Handler: 'com.hindu.horoscope.function.HoroscopeHandler::handleRequest'
      Runtime: java8
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          API_KEY: '1234'
          BASE_URL: '1123123'
          HOROSCOPE_LOCALES: 'en,hi'
      Role: >-
        arn:aws:iam::450848632298:role/service-role/testLambdaCloudWatchEvent-role-9b3johvi
      PackageType: Zip
